//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez odpowiednie narzędzie.
//
//     Zmiany w tym pliku mogą być przyczyną niepoprawnego zachowania i zostaną utracone w przypadku
//     ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Pages.AdministratorPages.OfficeManagement
{


    public partial class OfficesManagementPage
    {
    }
}
